### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by Nerens** [michaelliao/cryptocurrency#11]
Hi, are you buying cryptocurrency now? Is it worth buying at all?

**Comment by Vergisc** [comment]
I was saving my money to invest it in something on a crypto exchange. After hearing from friends about different exchanges, I was advised to [buy bitcoin with credit card](https://j2tx.com/buy-bitcoin/with-card) at j2tx.com.  They have their own app for smartphones. I immediately decided to use it and was very satisfied. I will be buying from them in the future. They also have very responsive support who will help me with any questions.
