### ISSUE TITLE
Anyone have a good comparison spreadsheet of all the different cryptos?

### ISSUE THREAD

**Issue by UmaPaluma** [michaelliao/cryptocurrency#4]
Looking for something that shows different features: privacy protection, trusted setup, avg block time, PoW algorithm, etc, etc.

**Comment by JomanWalter** [comment]
There are major cryptocurrencies that have been underrated. Investing in those cryptocurrencies are opportunities a lot of people have not yet discovered. The cryptocurrencies that are underrated include ethereum, bitcoin cash, and Litecoin. You can make a [cryptocurrency compare](https://coin-cap.pro/en/compare/). And choice where that can be invested on the platform.

**Comment by Bilidova** [comment]
I think that there are a lot of them on the internet, but I've been using mostly BTC, and it works great for me. I'm a freelance designer and developer, so I don't use crypto for trading or other things. I prefer to be paid with it. To feel more confident, I decided to find a platform to work in and came across this site [https://laborx.com/](https://laborx.com/), where soon I'll start working. The only crypto is used there, so if someone is interested, check the website.

**Comment by Vergisc** [comment]
Hello, there are many varieties of cryptocurrency and none of them are stable, including dogecoin. If we talk about the purchase itself, I think that the easiest way is [buy bitcoin with visa](https://j2tx.com/buy-bitcoin/with-card) , by the way, you can make a purchase at j2tx.com , it is a very reliable service, with which I never had any problems.
